groups:
  arm:
    operating_mode: position
    profile_type: time
    profile_velocity: 2000
    profile_acceleration: 300
    torque_enable: true

singles:
  gripper:
    operating_mode: position   # use 'position' for radian commands (e.g. 0 = closed, ~0.8 = open); use 'pwm' for -885 to 885
    torque_enable: true
